### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Phyktion** [stevetasticsteve/Anki_bulk_importer#10]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "C:\Users\x\AppData\Roaming\Anki2\addons21\1312111882\__init__.py", line 17, in CLAImporter
    bulk_importer.run()
  File "C:\Users\x\AppData\Roaming\Anki2\addons21\1312111882\bulk_importer.py", line 350, in run
    Window(aqt.mw)
  File "C:\Users\x\AppData\Roaming\Anki2\addons21\1312111882\bulk_importer.py", line 73, in __init__
    self.deckLabel.setAlignment(aqt.qt.Qt.AlignVCenter | aqt.qt.Qt.AlignRight)
AttributeError: type object 'Qt' has no attribute 'AlignVCenter'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Bulk importer ['1312111882', 2023-05-04T06:33, 'None', '']

===IDs of active AnkiWeb add-ons===
1312111882

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by v0ry** [comment]
I fixt it... I created a mearg i post the link in a sec. just let me push

**Comment by v0ry** [comment]
https://github.com/v0ry/Anki_bulk_importer
